### PR TITLE
[#5] Unwrap dimensions properly

### PR DESCRIPTION
**Pull request by yumeto**
- Parse the dimensions value by format_param/1 instead of format/2
- Add Example document (as doctest for minimum parameter set)
- Add UT. put_metric_data for full parameter set

### CODE REVIEW

**Comment by yumeto** [comment]
@CaldwellYSR 
Can you review my solution, inspired by yours.
Feel free to pick, change or use a part or whole of my commit, as you like. 

Please merge this PR if you would like.
Thanks!

**Comment by CaldwellYSR** [comment]
I will review when I get back home. Currently having airport adventures. Could be tonight or a few days.

**Comment by yumeto** [comment]
Wow! Have a good trip!

**Review by CaldwellYSR — CHANGES_REQUESTED** [review]
Do we need to map this twice? Couldn't we skip the first map and do something like: 

```
metric_data
|> Enum.map(fn(metric_datum) -> format_param({:metric_datum, metric_datum}) end)
|> format(...)
```

**Review by CaldwellYSR — APPROVED** [review]

**Comment by yumeto** [comment]
@CaldwellYSR Thanks for reviewing and improving.

**Pull request merged**
